FROM node:20-alpine

WORKDIR /server

# Copiar package.json e instalar solo dependencias de producción
COPY package*.json ./
RUN npm install --production

# Copiar el código
COPY . .

# Exponer puerto del API
EXPOSE 4000

# Ejecutar la app con Node
CMD ["node", "src/index.js"]
