# Backend: Node + Nodemon para hot reload
FROM node:20

WORKDIR /server

# Copiar package.json e instalar dependencias
COPY package*.json ./
RUN npm install
RUN npm install -g nodemon

# Copiar el resto del código
COPY . .

# Exponer puerto
EXPOSE 4000

# Comando para desarrollo
CMD ["nodemon", "src/index.js"]